### ISSUE TITLE
[Device-SDK-C] device-service operatingState doesn't go down post device-service stop

### ISSUE THREAD

**Issue by nil4git** [edgexfoundry/device-sdk-c#356]
On stopping the device service which internally calls the devsdk_service_stop() & devsdk_service_free() function but the OperatingState of the device still remains in UP state 

Instead with explicit calls to devsdk_service_stop() this should notify the metadata and eventually should make the device down/unavailable as well

**Comment by iain-anderson** [comment]
Raised in WG meeting 12th July. OperatingState set to DOWN is currently intended to indicate a failure condition on the device. It's not clear that having it indicate a more general inaccessibility due to device service shutdown is beneficial. Is there a use case for this where existing diagnostic possibilities (eg querying service health via consul) is insufficient?
(Also noted that a device being unexpectedly unavailable due to the service not running is likely to be the result of service crash, in which case the clean shutdown path would not have been taken)

**Comment by nil4git** [comment]
In such case, can't the exiting state be extended to indicate something like closed or exited as well, coz this can be handy to check at times before re/launching the device

**Comment by lindseysimple** [comment]
Closing this as a wontfix.
